FROM python:3.13-slim

ENV DEBIAN_FRONTEND=noninteractive

# 换源
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources \
    && apt update

# 常用工具
RUN apt install -y iputils-ping ssh git

# 安装ansible
RUN pip install ansible